### ISSUE TITLE
파일 수정 권한 오류

### ISSUE THREAD

**Issue by k296070** [LISTatSNU/FastMRI_challenge#21]
안녕하세요

제가 제작한 모델들과 제공해주신 기본 Unet 모두에서 다음과같은 에러가 발생합니다.
혹시 해결방법을 아시는 분이 있으실까요??
다음 두 링크를 참고하여 해결해보려 하였습니다.

https://stackoverflow.com/questions/13207450/permissionerror-errno-13-in-python
https://github.com/thtrieu/darkflow/issues/876

`ssh://student@147.46.92.222:22412/bin/python3 -u /home/student/fastMRI/Code/train.py
Current cuda device:  0
Epoch # 1 ............... test_Unet ...............
/usr/local/lib/python3.8/dist-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
Epoch = [  1/ 25] Iter = [   0/1244] Loss = 0.6803 Time = 0.0619s
Epoch = [  1/ 25] Iter = [ 500/1244] Loss = 0.2977 Time = 0.0515s
Epoch = [  1/ 25] Iter = [1000/1244] Loss = 0.09293 Time = 0.0515s
Traceback (most recent call last):
  File "/home/student/fastMRI/Code/train.py", line 37, in <module>
    train(args)
  File "/home/student/fastMRI/Code/utils/learning/train_part.py", line 125, in train
    save_model(args, args.exp_dir, epoch + 1, model, optimizer, best_val_loss, is_new_best)
  File "/home/student/fastMRI/Code/utils/learning/train_part.py", line 83, in save_model
    torch.save(
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 376, in save
    with _open_file_like(f, 'wb') as opened_file:
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
PermissionError: [Errno 13] Permission denied: '../result/test_Unet/checkpoints/model.pt'
`

**Comment by k296070** [comment]
파일 디렉토리를 명확하게 하니 해결이 되네요.
