### ISSUE TITLE
Colab에서 데이터를 불러올 때 발생하는 문제

### ISSUE THREAD

**Issue by torytony24** [LISTatSNU/FastMRI_challenge#248]
안녕하세요 달팽이 팀입니다.
GPU를 할당받지 못해 Colab Pro를 이용해 진행 중인데, 런타임 실행을 할 때 마다 train.py 코드 실행 여부가 수시로 달라져 질문드립니다.

다음과 같은 command로 Google drive mount를 하고 Colab을 통해 root와 home에 파일을 복사하고 실행했습니다. 
```
from google.colab import drive
drive.mount ('/content/drive')

!cp -r /content/drive/MyDrive/home/Data /home
!cp -r /content/drive/MyDrive/root/FastMRI_challenge /root

import os
os.chdir("/root/FastMRI_challenge")

!sh train.sh
```
train 파일 실행 결과 에러가 발생하지 않고 성공적으로 SSIM까지 도출될 때가 있는 반면, train을 실행하고 다음과 같은 에러메시지가 나올 때도 있었습니다.
```
Current cuda device:  0
Traceback (most recent call last):
  File "/root/FastMRI_challenge/train.py", line 50, in <module>
    train(args)
  File "/root/FastMRI_challenge/utils/learning/train_part.py", line 110, in train
    train_loader = create_data_loaders(data_path = args.data_path_train, args = args, shuffle=True)
  File "/root/FastMRI_challenge/utils/data/load_data.py", line 50, in create_data_loaders
    data_storage = SliceData(
  File "/root/FastMRI_challenge/utils/data/load_data.py", line 17, in __init__
    num_slices = self._get_metadata(fname)
  File "/root/FastMRI_challenge/utils/data/load_data.py", line 24, in _get_metadata
    with h5py.File(fname, "r") as hf:
  File "/usr/local/lib/python3.10/dist-packages/h5py/_hl/files.py", line 567, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/usr/local/lib/python3.10/dist-packages/h5py/_hl/files.py", line 231, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 106, in h5py.h5f.open
ConnectionAbortedError: [Errno 103] Unable to open file (file read failed: time = Sat Jul 13 01:42:31 2024
, filename = '/home/Data/train/image/brain_acc4_101.h5', file descriptor = 37, errno = 103, error message = 'Software caused connection abort', buf = 0x574987998ed0, total read size = 88, bytes this sub-read = 88, bytes actually read = 18446744073709551615, offset = 0)
```
파일을 열 수 없다는 에러인데, 에러메세지를 보면 101번 파일 `/home/Data/train/image/brain_acc4_101.h5`를 열 수 없다고 합니다. 경우에 따라 이 파일이 102번 파일일 때도 있습니다. 매 실행마다 열리지 않는 파일이 달라지는 이유를 모르겠습니다.

Colab T4 GPU의 리소스를 확인해 본 결과 다음과 같이 시스템 RAM이 피크를 찍었다가 돌아왔습니다. 
<img width="311" alt="화면 캡처 2024-07-13 105947" src="https://github.com/user-attachments/assets/e63ed937-fb05-4b2d-9d41-4494fb004ad7">

구글 드라이브에서 데이터를 받아오기 때문에 RAM에 데이터를 모두 저장한 후 코드를 실행해서 용량이 다 차고, 여기서 문제가 발생했을 수도 있을 것 같습니다. 아니면 에러메시지의 `'Software caused connection abort'`로 보아 구글 드라이브 권한을 통해 데이터를 받아오는 과정에서 문제가 생겼을지, 단순히 `h5py`파일 자체의 문제인지 궁금합니다.

이 문제를 해결하면 원활하게 챌린지를 진행할 수 있을 것 같습니다. 감사합니다.

**Comment by yxxshin** [comment]
안녕하세요,

정확한 이유는 잘 모르겠지만 특정 파일이 열릴 때도 있고 그렇지 않을 때도 있다면 파일 자체의 문제는 아닐 것 같습니다. Google Drive 의 안정성 문제 때문인 것 같은데, 혹시 다음과 같이 `/content` 디렉토리로 파일들을 복사해서 사용할 때도 같은 현상이 일어나나요?

```
!cp -r /content/drive/MyDrive/home/Data /content/home
!cp -r /content/drive/MyDrive/root/FastMRI_challenge /content/root
```

제가 알고 있기론 `/content` 에 저장을 하는 것이 조금 더 안정적이어서 추천 드려봅니다.

추가로, Colab으로 전체 dataset을 이용하여 training 하는 것은 위 문제와 같이 많이 불안정하기 때문에 추천드리지 않습니다. 데이터셋의 일부만 사용하셔서 각종 실험 및 검증을 한 후, 전체 데이터로의 실험은 GPU 서버에서 진행하시는 것을 권장드립니다.
