### ISSUE TITLE
GPU 서버 정상화 이후 image 디렉토리 관련 오류

### ISSUE THREAD

**Issue by journewki** [LISTatSNU/FastMRI_challenge#262]
안녕하세요. 서버 정상화 이후 다른 부분은 아예 손댄 것 없이 다시 세팅을 하여 python train.py 명령어를 실행하는데 아래와 같은 오류 문구가 떠서 문의드립니다. 직접 디렉토리 확인했을때 존재하는데 왜 이런 오류가 뜨는 것인지 모르겠습니다. 

`root@workspace-kphxm7y3n4d9-0:~/FastMRI_challenge# python train.py
Current cuda device:  0
Traceback (most recent call last):
  File "train.py", line 54, in <module>
    train(args)
  File "/root/FastMRI_challenge/utils/learning/train_part.py", line 149, in train
    train_loader = create_data_loaders(data_path = args.data_path_train, args = args, shuffle=True)
  File "/root/FastMRI_challenge/utils/data/load_data.py", line 72, in create_data_loaders
    data_storage = SliceData(
  File "/root/FastMRI_challenge/utils/data/load_data.py", line 18, in __init__
    image_files = list(Path(root / "image").iterdir())
  File "/usr/lib/python3.8/pathlib.py", line 1122, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [Errno 2] No such file or directory: '/Data/train/image'`

**Comment by yxxshin** [comment]
안녕하세요,

서버 번호 (IABENG ??) 를 알려주시기 바랍니다.

감사합니다.

**Comment by journewki** [comment]
33번 입니다! 아직 논문 스터디 중이어서 서버는 아무것도 건든 것이 없습니다

**Comment by yxxshin** [comment]
제가 직접 IABENG 33 접속했을 때에는 Data가 서버 안에 있는 것으로 확인이 됩니다.

현재 VESSL이 2.0 으로 사이트가 업데이트 되었는데, #261 과 같이 사이트 버전을 낮춘 후 기존에 YouTube 및 메일에서 알려드린 대로 Storage mount 를 진행하셨을까요?

**Comment by jslee525** [comment]
안녕하세요, 2024 SNU FastMRI Challenge 조교 이준성입니다.

33번 서버를 확인해보았는데 정상적으로 data mount가 되어있습니다.
혹시 명령어를 정확히 입력하신 걸까요?
Error Message 중에 FileNotFoundError: [Errno 2] No such file or directory: '/Data/train/image' 에러가 있는데 Data 경로는 '/home/Data/train/image'입니다. 서버 상에서도 확인하실 수 있습니다.

확인 후에 이상이 있으실 경우 다시 알려주세요. 감사합니다.

이준성 드림
